---
agents:
  - ZeroShotAgent
  - JsonAgent
  - CSVAgent
  - AgentInitializer
  - VectorStoreAgent
  - VectorStoreRouterAgent
  - SQLAgent
chains:
  - LLMChain
  - LLMMathChain
  - LLMCheckerChain
  - ConversationChain
  - SeriesCharacterChain
  - MidJourneyPromptChain
  - TimeTravelGuideChain
  - SQLDatabaseChain
  - RetrievalQA
  - RetrievalQAWithSourcesChain
  - ConversationalRetrievalChain
  - CombineDocsChain
documentloaders:
  - AirbyteJSONLoader
  - CoNLLULoader
  - CSVLoader
  - UnstructuredEmailLoader
  - EverNoteLoader
  - FacebookChatLoader
  - GutenbergLoader
  - BSHTMLLoader
  - UnstructuredHTMLLoader
  # - UnstructuredImageLoader # Issue with Python 3.11 (https://github.com/Unstructured-IO/unstructured-inference/issues/83)
  - UnstructuredMarkdownLoader
  - PyPDFLoader
  - UnstructuredPowerPointLoader
  - SRTLoader
  - TelegramChatLoader
  - TextLoader
  - UnstructuredWordDocumentLoader
  - WebBaseLoader
  - AZLyricsLoader
  - CollegeConfidentialLoader
  - HNLoader
  - IFixitLoader
  - IMSDbLoader
  - GitbookLoader
  - ReadTheDocsLoader
  - SlackDirectoryLoader
  - NotionDirectoryLoader
  - DirectoryLoader
  - GitLoader
embeddings:
  - OpenAIEmbeddings
  - HuggingFaceEmbeddings
  - CohereEmbeddings
llms:
  - OpenAI
  # - AzureOpenAI
  # - AzureChatOpenAI
  - ChatOpenAI
  - LlamaCpp
  - CTransformers
  - Cohere
  - Anthropic
  - ChatAnthropic
  - HuggingFaceHub
memories:
  - ConversationBufferMemory
  - ConversationSummaryMemory
  - ConversationKGMemory
prompts:
  - PromptTemplate
  - FewShotPromptTemplate
  - ZeroShotPrompt
  - ChatPromptTemplate
  - SystemMessagePromptTemplate
  - AIMessagePromptTemplate
  - HumanMessagePromptTemplate
  - ChatMessagePromptTemplate
textsplitters:
  - CharacterTextSplitter
  - RecursiveCharacterTextSplitter
  # - LatexTextSplitter
  # - PythonCodeTextSplitter
toolkits:
  - OpenAPIToolkit
  - JsonToolkit
  - VectorStoreInfo
  - VectorStoreRouterToolkit
  - VectorStoreToolkit
tools:
  - Search
  - PAL-MATH
  - Calculator
  - Serper Search
  - Tool
  - CustomComponent
  - PythonFunctionTool
  - PythonFunction
  - JsonSpec
  - News API
  - TMDB API
  - Podcast API
  - QuerySQLDataBaseTool
  - InfoSQLDatabaseTool
  - ListSQLDatabaseTool
  # - QueryCheckerTool
  - BingSearchRun
  - GoogleSearchRun
  - GoogleSearchResults
  - GoogleSerperRun
  - JsonListKeysTool
  - JsonGetValueTool
  - PythonREPLTool
  - PythonAstREPLTool
  - RequestsGetTool
  - RequestsPostTool
  - RequestsPatchTool
  - RequestsPutTool
  - RequestsDeleteTool
  - WikipediaQueryRun
  - WolframAlphaQueryRun
utilities:
  - BingSearchAPIWrapper
  - GoogleSearchAPIWrapper
  - GoogleSerperAPIWrapper
  - SearxResults
  - SearxSearchWrapper
  - SerpAPIWrapper
  - WikipediaAPIWrapper
  - WolframAlphaAPIWrapper
  # - ZapierNLAWrapper
  - SQLDatabase
vectorstores:
  - Chroma
  - Qdrant
  - Weaviate
  - FAISS
  - Pinecone
  - SupabaseVectorStore
  - MongoDBAtlasVectorSearch
wrappers:
  - RequestsWrapper
output_parsers:
  - StructuredOutputParser
  - ResponseSchema
